"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { apiFetch } from "@/lib/api-fetch";

const countFields = [["impressions","展示"],["views","播放"],["engagements","互动"],["clicks","点击"],["leads","线索"],["qualifiedLeads","有效线索"],["appointments","预约"],["quotes","报价"],["wins","成交"]] as const;
export default function MarketingMetricsPage(){
  const [form,setForm]=useState<Record<string,string>>({capturedAt:new Date().toISOString().slice(0,10),source:"manual",impressions:"0",views:"0",engagements:"0",clicks:"0",leads:"0",qualifiedLeads:"0",appointments:"0",quotes:"0",wins:"0",spend:"0",revenue:"0",currency:"CAD"});const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
  async function submit(e:FormEvent){e.preventDefault();setError(null);const response=await apiFetch("/api/marketing/metrics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const body=await response.json();if(!response.ok)return setError(body.error||"录入失败");setMessage("渠道数据已保存，并已计入增长执行力和推广日报。 ");}
  return <div className="mx-auto max-w-4xl space-y-5"><div><Link href="/operations/growth" className="text-sm text-accent">← 返回增长中心</Link><h1 className="mt-2 text-2xl font-bold">手动录入渠道数据</h1><p className="mt-1 text-sm text-muted">统一接口已预留 provider、外部账号和 raw 数据，后续可无缝替换为 GSC、GA4、GBP、Meta 与 TikTok 同步。</p></div>{error&&<div className="rounded-lg border border-red-300 bg-red-50 p-3 text-sm text-red-800">{error}</div>}{message&&<div className="rounded-lg border border-emerald-300 bg-emerald-50 p-3 text-sm text-emerald-800">{message}</div>}<form onSubmit={submit} className="space-y-5 rounded-xl border border-border bg-card-bg p-5"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm"><span className="mb-1 block text-muted">数据日期</span><input type="date" value={form.capturedAt} onChange={e=>setForm({...form,capturedAt:e.target.value})} className="w-full rounded-lg border border-border bg-background px-3 py-2"/></label><label className="text-sm"><span className="mb-1 block text-muted">来源</span><select value={form.source} onChange={e=>setForm({...form,source:e.target.value})} className="w-full rounded-lg border border-border bg-background px-3 py-2"><option value="manual">手动录入</option><option value="csv">CSV 导入</option></select></label></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{countFields.map(([key,label])=><label key={key} className="text-sm"><span className="mb-1 block text-muted">{label}</span><input type="number" min="0" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="w-full rounded-lg border border-border bg-background px-3 py-2"/></label>)}</div><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm"><span className="mb-1 block text-muted">广告花费</span><input type="number" min="0" step="0.01" value={form.spend} onChange={e=>setForm({...form,spend:e.target.value})} className="w-full rounded-lg border border-border bg-background px-3 py-2"/></label><label className="text-sm"><span className="mb-1 block text-muted">成交贡献</span><input type="number" min="0" step="0.01" value={form.revenue} onChange={e=>setForm({...form,revenue:e.target.value})} className="w-full rounded-lg border border-border bg-background px-3 py-2"/></label><label className="text-sm"><span className="mb-1 block text-muted">币种</span><input value={form.currency} maxLength={3} onChange={e=>setForm({...form,currency:e.target.value})} className="w-full rounded-lg border border-border bg-background px-3 py-2"/></label></div><button className="rounded-lg bg-accent px-5 py-2.5 text-sm font-medium text-white">保存渠道快照</button></form></div>;
}
