/**
 * 未 migrate 环境可用的 Project select（不得引用本 PR 新增列/关系）。
 * Prisma 默认会 SELECT 全部标量列，故必须显式 select 排除 bidPhaseStatus。
 */

/** 列表用：与历史 projectInclude 对齐，无 intelligenceRoom / bidPhaseStatus */
export const LEGACY_PROJECT_LIST_SELECT = {
  id: true,
  orgId: true,
  name: true,
  description: true,
  color: true,
  status: true,
  abandonedAt: true,
  createdAt: true,
  updatedAt: true,
  intakeStatus: true,
  sourceSystem: true,
  solicitationNumber: true,
  clientOrganization: true,
  closeDate: true,
  owner: { select: { id: true, name: true } },
  _count: { select: { tasks: true, environments: true } },
} as const;

/** 详情用：主体 + 既有关联，无 intelligenceRoom / bidPhaseStatus */
export const LEGACY_PROJECT_DETAIL_SELECT = {
  id: true,
  orgId: true,
  workspaceId: true,
  name: true,
  code: true,
  description: true,
  color: true,
  status: true,
  startDate: true,
  dueDate: true,
  workDomain: true,
  deliveryStage: true,
  plannedCompletionDate: true,
  actualCompletionDate: true,
  createdAt: true,
  updatedAt: true,
  category: true,
  priority: true,
  tenderStatus: true,
  sourceSystem: true,
  sourcePlatform: true,
  clientOrganization: true,
  location: true,
  estimatedValue: true,
  currency: true,
  ourBidPrice: true,
  winningBidPrice: true,
  projectTypes: true,
  aiAdviceStatus: true,
  solicitationNumber: true,
  workflowTemplate: true,
  sourceMetadataJson: true,
  publicDate: true,
  questionCloseDate: true,
  closeDate: true,
  openDate: true,
  distributedAt: true,
  dispatchedAt: true,
  intakeStatus: true,
  interpretedAt: true,
  supplierInquiredAt: true,
  supplierQuotedAt: true,
  submittedAt: true,
  awardDate: true,
  abandonedAt: true,
  abandonedStage: true,
  abandonedReason: true,
  ownerId: true,
  purchaserId: true,
  owner: { select: { id: true, name: true, email: true } },
  purchaser: { select: { id: true, name: true, email: true } },
  org: { select: { id: true, name: true, code: true, status: true } },
  _count: { select: { tasks: true, environments: true, members: true } },
  externalRef: true,
  intelligence: true,
  documents: {
    select: {
      id: true,
      title: true,
      url: true,
      fileType: true,
      fileSize: true,
      sortOrder: true,
      parseStatus: true,
      aiSummaryStatus: true,
      source: true,
      createdAt: true,
    },
    orderBy: { sortOrder: "asc" as const },
  },
} as const;
