"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { apiFetch } from "@/lib/api-fetch";
import { DIMENSION_LABELS, MARKETING_DIMENSIONS } from "@/lib/marketing/constants";

export default function MarketingAuditPage() {
  const [scores,setScores]=useState<Record<string,string>>(Object.fromEntries(MARKETING_DIMENSIONS.map(d=>[d,"0"])));
  const [context,setContext]=useState({geography:"",industry:"",product:"",competitors:"",query:""});
  const [finding,setFinding]=useState({dimension:"AI_VISIBILITY",severity:"high",title:"",description:"",currentValue:"",expectedValue:""});
  const [message,setMessage]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
  async function submit(event:FormEvent){event.preventDefault();setError(null);setMessage(null);const response=await apiFetch("/api/marketing/audits",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({source:"manual",confidence:100,contexts:[{...context,competitors:context.competitors.split(/\n|,/).filter(Boolean)}],scores:MARKETING_DIMENSIONS.map(d=>({dimension:d,score:Number(scores[d]),confidence:100})),findings:finding.title?[finding]:[]})});const body=await response.json();if(!response.ok)return setError(`${body.error||"保存失败"}${body.issues?.length?`：${body.issues.map((i:{message:string})=>i.message).join("；")}`:""}`);setMessage(`体检已保存，总分 ${body.audit.totalScore}/100`);}
  return <div className="mx-auto max-w-5xl space-y-5"><div><Link href="/operations/growth" className="text-sm text-accent">← 返回增长中心</Link><h1 className="mt-2 text-2xl font-bold">手动录入营销体检</h1><p className="mt-1 text-sm text-muted">Phase 1 先建立可信基线。所有上下文必须通过企业事实校验，否则整次检测无效且不计分。</p></div>{error&&<div className="rounded-lg border border-red-300 bg-red-50 p-3 text-sm text-red-800">{error}</div>}{message&&<div className="rounded-lg border border-emerald-300 bg-emerald-50 p-3 text-sm text-emerald-800">{message}</div>}
    <form onSubmit={submit} className="space-y-5"><section className="rounded-xl border border-border bg-card-bg p-5"><h2 className="font-semibold">检测上下文</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{([['geography','地域'],['industry','行业'],['product','产品'],['competitors','竞争对手（逗号分隔）']] as const).map(([k,l])=><label key={k} className="text-sm"><span className="mb-1 block text-muted">{l}</span><input value={context[k]} onChange={e=>setContext({...context,[k]:e.target.value})} className="w-full rounded-lg border border-border bg-background px-3 py-2"/></label>)}<label className="text-sm sm:col-span-2"><span className="mb-1 block text-muted">测试问题/查询</span><textarea value={context.query} onChange={e=>setContext({...context,query:e.target.value})} className="w-full rounded-lg border border-border bg-background px-3 py-2" rows={3}/></label></div></section>
      <section className="rounded-xl border border-border bg-card-bg p-5"><h2 className="font-semibold">七维评分</h2><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{MARKETING_DIMENSIONS.map(d=><label key={d} className="text-xs"><span className="mb-1 block text-muted">{DIMENSION_LABELS[d]}</span><input type="number" min="0" max="100" value={scores[d]} onChange={e=>setScores({...scores,[d]:e.target.value})} className="w-full rounded-lg border border-border bg-background px-3 py-2 text-base"/></label>)}</div></section>
      <section className="rounded-xl border border-border bg-card-bg p-5"><h2 className="font-semibold">首个问题（可选）</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><select value={finding.dimension} onChange={e=>setFinding({...finding,dimension:e.target.value})} className="rounded-lg border border-border bg-background px-3 py-2">{MARKETING_DIMENSIONS.map(d=><option key={d} value={d}>{DIMENSION_LABELS[d]}</option>)}</select><select value={finding.severity} onChange={e=>setFinding({...finding,severity:e.target.value})} className="rounded-lg border border-border bg-background px-3 py-2"><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><input placeholder="问题标题" value={finding.title} onChange={e=>setFinding({...finding,title:e.target.value})} className="rounded-lg border border-border bg-background px-3 py-2 sm:col-span-2"/><textarea placeholder="问题说明" value={finding.description} onChange={e=>setFinding({...finding,description:e.target.value})} className="rounded-lg border border-border bg-background px-3 py-2 sm:col-span-2" rows={3}/><input placeholder="当前值" value={finding.currentValue} onChange={e=>setFinding({...finding,currentValue:e.target.value})} className="rounded-lg border border-border bg-background px-3 py-2"/><input placeholder="目标值" value={finding.expectedValue} onChange={e=>setFinding({...finding,expectedValue:e.target.value})} className="rounded-lg border border-border bg-background px-3 py-2"/></div></section><button className="rounded-lg bg-accent px-5 py-2.5 text-sm font-medium text-white">保存可信体检</button></form>
  </div>;
}
