/**
 * 报价 PDF 签名盖章 — 客户在公开分享页签字后调用
 *
 * 以发送时存档的 Order Form PDF 为底，在末尾追加一页「Customer Acceptance」
 * 签署确认页（签名图 + 签署时间 + 报价引用），生成不可再覆盖的已签署 PDF。
 * 客户签的就是发出去的那份 PDF，杜绝网页渲染与 PDF 内容不一致的问题。
 */

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { readBlobBuffer, putPrivateBlob } from "@/lib/files/blob-access";

const ORANGE = rgb(234 / 255, 88 / 255, 12 / 255);
const TEXT_MAIN = rgb(28 / 255, 25 / 255, 23 / 255);
const TEXT_MUTED = rgb(120 / 255, 113 / 255, 108 / 255);

export interface StampSignatureArgs {
  quoteId: string;
  /** 发送时存档的 PDF（私有 Blob pathname） */
  pdfPath: string;
  /** 客户手写签名 data URL（data:image/png;base64,...） */
  signatureDataUrl: string;
  customerName: string;
  orderNumber: string | null;
  signedAt: Date;
}

/** 返回已签署 PDF 的私有 Blob pathname */
export async function stampSignatureIntoQuotePdf(
  args: StampSignatureArgs,
): Promise<string> {
  const source = await readBlobBuffer(args.pdfPath);
  if (!source) {
    throw new Error(`报价 PDF 读取失败: ${args.pdfPath}`);
  }

  const pdf = await PDFDocument.load(source.buffer);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const base64 = args.signatureDataUrl.replace(/^data:image\/\w+;base64,/, "");
  const sigImage = await pdf.embedPng(Buffer.from(base64, "base64"));

  // A4 尺寸对齐原 PDF（jsPDF A4 = 595.28 × 841.89 pt）
  const [firstPage] = pdf.getPages();
  const { width: pageW, height: pageH } = firstPage.getSize();
  const page = pdf.addPage([pageW, pageH]);

  const margin = 40;
  let y = pageH - margin - 20;

  // 顶部橙色条 + 标题
  page.drawRectangle({ x: 0, y: pageH - 8, width: pageW, height: 8, color: ORANGE });
  page.drawText("CUSTOMER ACCEPTANCE", {
    x: margin,
    y,
    size: 22,
    font: fontBold,
    color: TEXT_MAIN,
  });
  y -= 16;
  page.drawText("Signed order confirmation", {
    x: margin,
    y,
    size: 10,
    font,
    color: TEXT_MUTED,
  });
  y -= 36;

  const drawField = (label: string, value: string) => {
    page.drawText(label.toUpperCase(), {
      x: margin,
      y,
      size: 8,
      font,
      color: TEXT_MUTED,
    });
    page.drawText(value, {
      x: margin,
      y: y - 14,
      size: 12,
      font: fontBold,
      color: TEXT_MAIN,
    });
    y -= 42;
  };

  drawField("Order Reference", args.orderNumber || args.quoteId);
  drawField("Customer", args.customerName);
  drawField(
    "Signed At",
    args.signedAt.toLocaleString("en-CA", { timeZone: "America/Toronto" }),
  );

  // 签名图（等比缩放，最大宽 260pt / 高 100pt）
  y -= 10;
  page.drawText("SIGNATURE", { x: margin, y, size: 8, font, color: TEXT_MUTED });
  y -= 8;
  const maxW = 260;
  const maxH = 100;
  const scale = Math.min(maxW / sigImage.width, maxH / sigImage.height, 1);
  const sigW = sigImage.width * scale;
  const sigH = sigImage.height * scale;
  page.drawImage(sigImage, { x: margin, y: y - sigH, width: sigW, height: sigH });
  page.drawLine({
    start: { x: margin, y: y - sigH - 6 },
    end: { x: margin + Math.max(sigW, 200), y: y - sigH - 6 },
    thickness: 1,
    color: TEXT_MUTED,
  });
  y -= sigH + 30;

  page.drawText(
    "By signing above, the customer confirms this order and agrees to the pricing,",
    { x: margin, y, size: 9, font, color: TEXT_MUTED },
  );
  y -= 13;
  page.drawText(
    "product specifications and terms set out in the preceding pages of this document.",
    { x: margin, y, size: 9, font, color: TEXT_MUTED },
  );

  // 页脚
  page.drawText(
    `Document ID: ${args.quoteId} · Generated by Qingyan on ${args.signedAt.toISOString()}`,
    { x: margin, y: 24, size: 7, font, color: TEXT_MUTED },
  );

  const bytes = await pdf.save();
  const signedPath = `sales-quotes/${args.quoteId}/order-signed-${Date.now()}.pdf`;
  await putPrivateBlob({
    pathname: signedPath,
    body: Buffer.from(bytes),
    contentType: "application/pdf",
  });
  return signedPath;
}
