/**
 * 报价单 PDF 导出 — 客户端生成
 *
 * 使用 jsPDF + jspdf-autotable，支持中文（内嵌 NotoSansSC 子集太大，
 * 当前用 helvetica 兜底 + CJK fallback 会显示方块；
 * 为 MVP 采用英文为主 + 中文字段做 ASCII 替换的方式）。
 *
 * 后续可替换为服务端 Puppeteer 方案以完美支持中文。
 */

import type { QuoteHeaderData, QuoteLineItemData } from "./types";
import type { QuoteTotals } from "./calculate";
import { TEMPLATE_LABELS } from "./types";

interface ExportPdfOptions {
  header: QuoteHeaderData;
  lines: QuoteLineItemData[];
  totals: QuoteTotals;
  projectName: string;
  quoteVersion?: number;
}

const CATEGORY_EN: Record<string, string> = {
  product: "Product",
  shipping: "Shipping",
  customs: "Customs",
  packaging: "Packaging",
  labor: "Labor",
  overhead: "Overhead",
  tax: "Tax",
  other: "Other",
};

function fmt(n: number | null): string {
  if (n == null) return "-";
  return n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export async function exportQuotePdf(opts: ExportPdfOptions) {
  const { header, lines, totals, projectName, quoteVersion } = opts;
  const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("QUOTATION", pageWidth / 2, 20, { align: "center" });

  // Subtitle / project
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(header.title || "Untitled Quote", pageWidth / 2, 27, { align: "center" });
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(`Project: ${projectName}${quoteVersion ? ` | Version ${quoteVersion}` : ""}`, pageWidth / 2, 32, { align: "center" });
  doc.setTextColor(0);

  // Header info
  let y = 40;
  doc.setFontSize(9);
  const headerFields: [string, string][] = [
    ["Template", TEMPLATE_LABELS[header.templateType] ?? header.templateType],
    ["Currency", header.currency],
    ["Trade Terms", header.tradeTerms || "-"],
    ["Payment Terms", header.paymentTerms || "-"],
    ["Delivery", header.deliveryDays ? `${header.deliveryDays} days` : "-"],
    ["Valid Until", header.validUntil || "-"],
    ["MOQ", header.moq ? String(header.moq) : "-"],
    ["Origin", header.originCountry || "-"],
  ];

  const colW = (pageWidth - 30) / 2;
  for (let i = 0; i < headerFields.length; i += 2) {
    const [k1, v1] = headerFields[i];
    doc.setFont("helvetica", "bold");
    doc.text(`${k1}:`, 15, y);
    doc.setFont("helvetica", "normal");
    doc.text(v1, 45, y);

    if (i + 1 < headerFields.length) {
      const [k2, v2] = headerFields[i + 1];
      doc.setFont("helvetica", "bold");
      doc.text(`${k2}:`, 15 + colW, y);
      doc.setFont("helvetica", "normal");
      doc.text(v2, 45 + colW, y);
    }
    y += 5;
  }

  y += 4;

  // Line items table
  const tableHead = [["#", "Category", "Item", "Spec", "Unit", "Qty", "Unit Price", "Total"]];
  const tableBody = lines.map((line, idx) => [
    String(idx + 1),
    CATEGORY_EN[line.category] ?? line.category,
    line.itemName || "-",
    line.specification || "-",
    line.unit || "-",
    line.quantity != null ? String(line.quantity) : "-",
    fmt(line.unitPrice),
    fmt(line.totalPrice),
  ]);

  autoTable(doc, {
    startY: y,
    head: tableHead,
    body: tableBody,
    theme: "striped",
    headStyles: { fillColor: [43, 96, 85], fontSize: 8, fontStyle: "bold" },
    bodyStyles: { fontSize: 7.5 },
    columnStyles: {
      0: { cellWidth: 8 },
      5: { halign: "right" },
      6: { halign: "right" },
      7: { halign: "right" },
    },
    margin: { left: 15, right: 15 },
  });

  // Totals after table
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const finalY = (doc as any).lastAutoTable?.finalY ?? y + 10;
  let ty = finalY + 8;

  doc.setFontSize(9);

  const totalsLines: [string, string][] = [
    ["Subtotal", `${header.currency} ${fmt(totals.subtotal)}`],
    ["Total Amount", `${header.currency} ${fmt(totals.totalAmount)}`],
  ];
  if (totals.profitMargin != null) {
    totalsLines.push(["Profit Margin", `${totals.profitMargin}%`]);
  }

  for (const [label, value] of totalsLines) {
    doc.setFont("helvetica", "bold");
    doc.text(label + ":", pageWidth - 70, ty);
    doc.setFont("helvetica", "normal");
    doc.text(value, pageWidth - 15, ty, { align: "right" });
    ty += 5;
  }

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(150);
  doc.text(
    `Generated by QingYan AI | ${new Date().toISOString().slice(0, 10)}`,
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 8,
    { align: "center" }
  );

  const filename = `${header.title || "quote"}_v${quoteVersion ?? 1}.pdf`;
  doc.save(filename);
}
