import { NextResponse } from "next/server";
import { withAuth } from "@/lib/common/api-helpers";
import { db } from "@/lib/db";
import { resolveRequestOrgIdForUser } from "@/lib/auth/resolve-request-org";
import { requireMarketingWriteAccess } from "@/lib/marketing/access";
import { logAudit } from "@/lib/audit/logger";

export const GET=withAuth(async(request,_ctx,user)=>{const orgRes=await resolveRequestOrgIdForUser(user,request.nextUrl.searchParams.get("orgId"));if(!orgRes.ok)return orgRes.response;return NextResponse.json({attributions:await db.marketingLeadAttribution.findMany({where:{orgId:orgRes.orgId},include:{campaign:{select:{id:true,name:true}}},orderBy:{createdAt:"desc"},take:100})});});
export const POST=withAuth(async(request,_ctx,user)=>{const body=await request.json().catch(()=>({}));const orgRes=await resolveRequestOrgIdForUser(user,body.orgId);if(!orgRes.ok)return orgRes.response;const denied=await requireMarketingWriteAccess(user,orgRes.orgId);if(denied)return denied;const [campaign,opportunity]=await Promise.all([db.marketingCampaign.findFirst({where:{id:String(body.campaignId||""),orgId:orgRes.orgId},select:{id:true}}),db.salesOpportunity.findFirst({where:{id:String(body.salesOpportunityId||""),orgId:orgRes.orgId},select:{id:true,estimatedValue:true}})]);if(!campaign||!opportunity)return NextResponse.json({error:"活动或 CRM 商机不存在/跨组织"},{status:400});const attribution=await db.marketingLeadAttribution.upsert({where:{orgId_campaignId_salesOpportunityId:{orgId:orgRes.orgId,campaignId:campaign.id,salesOpportunityId:opportunity.id}},create:{orgId:orgRes.orgId,campaignId:campaign.id,salesOpportunityId:opportunity.id,publicationId:body.publicationId?String(body.publicationId):null,attributionModel:String(body.attributionModel||"manual"),confidence:Math.max(0,Math.min(100,Number(body.confidence??100))),attributedRevenue:body.attributedRevenue==null?opportunity.estimatedValue:Math.max(0,Number(body.attributedRevenue)||0),currency:String(body.currency||"CAD").slice(0,3).toUpperCase(),notes:body.notes?String(body.notes).slice(0,4000):null,createdById:user.id},update:{publicationId:body.publicationId?String(body.publicationId):null,confidence:Math.max(0,Math.min(100,Number(body.confidence??100))),attributedRevenue:body.attributedRevenue==null?opportunity.estimatedValue:Math.max(0,Number(body.attributedRevenue)||0),notes:body.notes?String(body.notes).slice(0,4000):null}});await logAudit({userId:user.id,orgId:orgRes.orgId,action:"marketing_lead_attribute",targetType:"marketing_lead_attribution",targetId:attribution.id,afterData:attribution,request});return NextResponse.json({attribution},{status:201});});
